version: "3.9"
services:
  dev-env:
    image: riskbert
    build: .
    tty: true
    volumes:
      - "/root"
      - ./:/app
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]